using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace CleanFiles.Config
{
	public class DefaultSettings
	{
		public static string GetDefaultSettings()
		{
			return 
"				{\n" +
"					\"Client\":\n" +
"					{\n" +
"					    \"Files\":\n" +
"					    [\n" +
"					        \"CleanLogs.exe\",\n" +
"					        \"Configuration.json\",\n" +
"					        \"BugTrap.dll\",\n" +
"				            \"d3dx9_25.dll\",\n" +
"				            \"dbghelp.dll\",\n" +
"				            \"Default.conf\",\n" +
"				            \"Fiesta.bin\",\n" +
"				            \"mss32.dll\",\n" +
"				            \"steam_api.dll\"\n" +
"				        ],\n" +
"				        \"Folders\":\n" +
"				        [\n" +
"				            {\n" +
"				                \"FolderName\": \"ressystem\",\n" +
"								\"Data\":" +
"								{\n" +
"									\"Files\":\n" +
"									[\n" +
"									    \"AbState.shn\",\n" +
"									    \"AbStateMsg.shn\",\n" +
"									    \"AbStateView.shn\",\n" +
"									    \"ActionEffectInfo.shn\",\n" +
"									    \"ActionEffectItem.shn\",\n" +
"									    \"ActionViewInfo.shn\",\n" +
"									    \"ActiveSkill.shn\",\n" +
"									    \"ActiveSkillGroup.shn\",\n" +
"									    \"ActiveSkillView.shn\",\n" +
"									    \"AttendReward.shn\",\n" +
"									    \"BadNameFilter.shn\",\n" +
"									    \"BasicInfoFind.shn\",\n" +
"									    \"BasicInfoFindUI.shn\",\n" +
"									    \"BasicInfoFindWord.shn\",\n" +
"									    \"BasicInfoHelp.shn\",\n" +
"									    \"BasicInfoLink.shn\",\n" +
"									    \"BasicInfoTip.shn\",\n" +
"									    \"BasicInfoTipCycle.shn\",\n" +
"									    \"BasicInfoTitle.shn\",\n" +
"									    \"BelongTypeInfo.shn\",\n" +
"									    \"BRAccUpgradeInfo.shn\",\n" +
"									    \"CharacterTitleData.shn\",\n" +
"									    \"CharacterTitleStateView.shn\",\n" +
"									    \"ChargedDeletableBuff.shn\",\n" +
"									    \"ChargedEffect.shn\",\n" +
"									    \"ChargedIconItem.shn\",\n" +
"									    \"ChargedMessageItem.shn\",\n" +
"									    \"ChatColor.shn\",\n" +
"									    \"ChrBasicEquip.shn\",\n" +
"									    \"ChrCreateEquip.shn\",\n" +
"									    \"ClassName.shn\",\n" +
"									    \"CollectCard.shn\",\n" +
"									    \"CollectCardGroupDesc.shn\",\n" +
"									    \"CollectCardReward.shn\",\n" +
"									    \"CollectCardTitle.shn\",\n" +
"									    \"CollectCardView.shn\",\n" +
"									    \"ColorInfo.shn\",\n" +
"									    \"DamageEffect.shn\",\n" +
"									    \"DamageSoundInfo.shn\",\n" +
"									    \"DiceDividind.shn\",\n" +
"									    \"EffectViewInfo.shn\",\n" +
"									    \"FaceCutMsg.shn\",\n" +
"									    \"FaceInfo.shn\",\n" +
"									    \"FontSet.shn\",\n" +
"									    \"Gather.shn\",\n" +
"									    \"GBDiceDividind.shn\",\n" +
"									    \"GBHouse.shn\",\n" +
"									    \"GradeItemOption.shn\",\n" +
"									    \"GTIView.shn\",\n" +
"									    \"GuildTournamentRequire.shn\",\n" +
"									    \"GuildTournamentSkill.shn\",\n" +
"									    \"GuildTournamentSkillDesc.shn\",\n" +
"									    \"HairColorInfo.shn\",\n" +
"									    \"HairInfo.shn\",\n" +
"									    \"ItemAction.shn\",\n" +
"									    \"ItemActionCondition.shn\",\n" +
"									    \"ItemActionEffect.shn\",\n" +
"									    \"ItemActionEffectDesc.shn\",\n" +
"									    \"ItemDismantle.shn\",\n" +
"									    \"ItemInfo.shn\",\n" +
"									    \"ItemMix.shn\",\n" +
"									    \"ItemMoney.shn\",\n" +
"									    \"ItemShopView.shn\",\n" +
"									    \"ItemViewDummy.shn\",\n" +
"									    \"ItemViewEquipTypeInfo.shn\",\n" +
"									    \"ItemViewInfo.shn\",\n" +
"									    \"KingdomQuestDesc.shn\",\n" +
"									    \"KQIsVote.shn\",\n" +
"									    \"KQTeam.shn\",\n" +
"									    \"KQVoteDesc.shn\",\n" +
"									    \"KQVoteMajorityRate.shn\",\n" +
"									    \"MapInfo.shn\",\n" +
"									    \"MapLinkPoint.shn\",\n" +
"									    \"MapViewInfo.shn\",\n" +
"									    \"MapWayPoint.shn\",\n" +
"									    \"MarketSearchInfo.shn\",\n" +
"									    \"MHEmotion.shn\",\n" +
"									    \"MiniHouse.shn\",\n" +
"									    \"MiniHouseEndure.shn\",\n" +
"									    \"MiniHouseFurniture.shn\",\n" +
"									    \"MiniHouseFurnitureObjEffect.shn\",\n" +
"									    \"MiniHouseObjAni.shn\",\n" +
"									    \"MinimonAutoUseItem.shn\",\n" +
"									    \"MinimonInfo.shn\",\n" +
"									    \"MobConditionView.shn\",\n" +
"									    \"MobCoordinate.shn\",\n" +
"									    \"MobInfo.shn\",\n" +
"									    \"MobKillAnnounceText.shn\",\n" +
"									    \"MobNoFadeIn.shn\",\n" +
"									    \"MobRandomIdleAni.shn\",\n" +
"									    \"MobViewInfo.shn\",\n" +
"									    \"MoverAbility.shn\",\n" +
"									    \"MoverHG.shn\",\n" +
"									    \"MoverItem.shn\",\n" +
"									    \"MoverMain.shn\",\n" +
"									    \"MoverSlotCharAni.shn\",\n" +
"									    \"MoverSlotView.shn\",\n" +
"									    \"MoverUpgradeEffect.shn\",\n" +
"									    \"MoverUseSkill.shn\",\n" +
"									    \"MoverView.shn\",\n" +
"									    \"NpcDialogData.shn\",\n" +
"									    \"NPCViewInfo.shn\",\n" +
"									    \"PassiveSkill.shn\",\n" +
"									    \"PassiveSkillView.shn\",\n" +
"									    \"Produce.shn\",\n" +
"									    \"ProduceView.shn\",\n" +
"									    \"PupMain.shn\",\n" +
"									    \"PupView.shn\",\n" +
"									    \"QuestData.shn\",\n" +
"									    \"QuestDialog.shn\",\n" +
"									    \"RaceNameInfo.shn\",\n" +
"									    \"Riding.shn\",\n" +
"									    \"ScriptMsg.shn\",\n" +
"									    \"SetEffect.shn\",\n" +
"									    \"SetItemName.shn\",\n" +
"									    \"SingleData.shn\",\n" +
"									    \"SlanderFilter.shn\",\n" +
"									    \"SubAbState.shn\",\n" +
"									    \"TermExtendMatch.shn\",\n" +
"									    \"TermExtendMatchGroupDesc.shn\",\n" +
"									    \"TextData.shn\",\n" +
"									    \"TextData2.shn\",\n" +
"									    \"TextData3.shn\",\n" +
"									    \"TownPortal.shn\",\n" +
"									    \"UpEffect.shn\",\n" +
"									    \"UpgradeInfo.shn\",\n" +
"									    \"UseClassTypeInfo.shn\",\n" +
"									    \"WeaponAttrib.shn\",\n" +
"									    \"WeaponTitleData.shn\",\n" +
"									    \"WorldMapAvatarInfo.shn\",\n" +
"									    \"blist.shd\",\n" +
"									    \"FinQuest.nif\",\n" +
"									    \"font.ini\",\n" +
"									    \"FPLIST.ons\",\n" +
"									    \"GetQuest.nif\",\n" +
"									    \"GetQuestLowLevel.nif\",\n" +
"									    \"IngQuest.nif\",\n" +
"									    \"Jump.nif\",\n" +
"									    \"KeyMapping.mco\",\n" +
"									    \"npcdlg.dat\",\n" +
"									    \"npcdlgbox.dat\",\n" +
"									    \"npctext.dat\",\n" +
"									    \"npctextbox.dat\",\n" +
"									    \"Option.mco\",\n" +
"									    \"OptionSound.mco\",\n" +
"									    \"SOrder.sdf\",\n" +
"									    \"WCInfo.hsb\"\n" +
"									]\n" +
"								}\n" +
"				            }\n" +
"				        ]\n" +
"				    },\n" +
"				    \"Server\":\n" +
"				    {\n" +
"				        \"Files\":\n" +
"				        [\n" +
"				            \"CleanLogs.exe\",\n" +
"				            \"Configuration.json\"\n" +
"				        ],\n" +
"				        \"Folders\":\n" +
"				        [\n" +
"				            {\n" +
"				                \"FolderName\": \"Account\",\n" +
"								\"Data\":" +
"								{\n" +
"									\"Files\":\n" +
"									[\n" +
"									    \"Account.exe\",\n" +
"									    \"DataServerInfo_Account.txt\"\n" +
"									]\n" +
"								}\n" +
"				            },\n" +
"				            {\n" +
"				                \"FolderName\": \"AccountLog\",\n" +
"								\"Data\":" +
"								{\n" +
"									\"Files\":\n" +
"									[\n" +
"									    \"AccountLog.exe\",\n" +
"									    \"DataServerInfo_AccountLog.txt\"\n" +
"									]\n" +
"								}\n" +
"							},\n" +
"				            {\n" +
"				                \"FolderName\": \"Character\",\n" +
"								\"Data\":" +
"								{\n" +
"									\"Files\":\n" +
"									[\n" +
"									    \"Character.exe\",\n" +
"									    \"DataServerInfo_Character.txt\"\n" +
"									]\n" +
"								}\n" +
"				            },\n" +
"				            {\n" +
"				                \"FolderName\": \"GameLog\",\n" +
"								\"Data\":" +
"								{\n" +
"									\"Files\":\n" +
"									[\n" +
"									    \"GameLog.exe\",\n" +
"									    \"DataServerInfo_GameLog.txt\"\n" +
"									]\n" +
"								}\n" +
"				            },\n" +
"				            {\n" +
"				                \"FolderName\": \"WorldManager\",\n" +
"								\"Data\":" +
"								{\n" +
"									\"Files\":\n" +
"									[\n" +
"									    \"WorldManager.exe\",\n" +
"									    \"WMServerInfo.txt\"\n" +
"									]\n" +
"								}\n" +
"				            },\n" +
"				            {\n" +
"				                \"FolderName\": \"Zone0\",\n" +
"								\"Data\":" +
"								{\n" +
"									\"Files\":\n" +
"									[\n" +
"									    \"Zone.exe\"\n" +
"									]\n" +
"								}\n" +
"				            },\n" +
"				            {\n" +
"				                \"FolderName\": \"Zone1\",\n" +
"								\"Data\":" +
"								{\n" +
"									\"Files\":\n" +
"									[\n" +
"									    \"Zone.exe\"\n" +
"									]\n" +
"								}\n" +
"				            },\n" +
"				            {\n" +
"				                \"FolderName\": \"Zone2\",\n" +
"								\"Data\":" +
"								{\n" +
"									\"Files\":\n" +
"									[\n" +
"									    \"Zone.exe\"\n" +
"									]\n" +
"								}\n" +
"				            },\n" +
"				            {\n" +
"				                \"FolderName\": \"Zone3\",\n" +
"								\"Data\":" +
"								{\n" +
"									\"Files\":\n" +
"									[\n" +
"									    \"Zone.exe\"\n" +
"									]\n" +
"								}\n" +
"				            },\n" +
"				            {\n" +
"				                \"FolderName\": \"Zone4\",\n" +
"								\"Data\":" +
"								{\n" +
"									\"Files\":\n" +
"									[\n" +
"									    \"Zone.exe\"\n" +
"									]\n" +
"								}\n" +
"				            }\n" +
"				        ]\n" +
"				    }\n" +
"				}";
		}
	}
}
